// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weysvjczxjxxvnghijol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndleXN2amN6eGp4eHZuZ2hpam9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzUyNTYsImV4cCI6MjA2NTU1MTI1Nn0.1Dimnh3nuWRdkXv3GFsMoQbn8ySm50Fs2q0SY47KzBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);